### ISSUE TITLE
"Flame on!" failed: function :erpc.call/4 is undefined (module :erpc is not available)

### ISSUE THREAD

**Issue by andiechu** [DockYard/flame_on#34]
Error log:

```
** (UndefinedFunctionError) function :erpc.call/4 is undefined (module :erpc is not available)
    :erpc.call(:nonode@nohost, FlameOn.Capture.Server, :start, [%FlameOn.Capture.Config{arity: 2, function: :execute, module: :cowboy_handler, reply_to: {:live_component, #PID<0.1699.0>, :flame_on_component}, target_node: :nonode@nohost, timeout: 15000}])
    (flame_on 0.5.2) lib/flame_on/capture.ex:6: FlameOn.Capture.capture/1
    (flame_on 0.5.2) lib/flame_on/component.ex:133: FlameOn.Component.handle_event/3
    (phoenix_live_view 0.17.14) lib/phoenix_live_view/channel.ex:600: anonymous fn/4 in Phoenix.LiveView.Channel.inner_component_handle_event/4
    (telemetry 1.2.1) /home/angdi/Documents/workspace/Timber_Server/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
    (phoenix_live_view 0.17.14) lib/phoenix_live_view/diff.ex:206: Phoenix.LiveView.Diff.write_component/4
    (phoenix_live_view 0.17.14) lib/phoenix_live_view/channel.ex:523: Phoenix.LiveView.Channel.component_handle_event/6
    (stdlib 3.12.1) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib 3.12.1) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib 3.12.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: %Phoenix.Socket.Message{event: "event", join_ref: "5", payload: %{"cid" => 1, "event" => "capture_schema", "type" => "form", "value" => "capture_schema%5Bmodule%5D=cowboy_handler&capture_schema%5Bfunction%5D=execute&capture_schema%5Barity%5D=2&capture_schema%5Btimeout%5D=15000"}, ref: "7", topic: "lv:phx-F33SQhksgdR0xQAI"}
State: %{components: {%{1 => {FlameOn.Component, :flame_on_component, %{__changed__: %{}, capture_changeset: #Ecto.Changeset<action: nil, changes: %{arity: 2, function: "execute", module: "cowboy_handler", timeout: 15000}, errors: [], data: #FlameOn.Component.CaptureSchema<>, valid?: true>, capture_timed_out?: false, capturing?: false, flash: %{}, id: :flame_on_component, myself: %Phoenix.LiveComponent.CID{cid: 1}, root_block: nil, target_node: :nonode@nohost, view_block_path: [], viewing_block: nil}, %{__changed__: %{}, root_view: Phoenix.LiveDashboard.PageLive}, {64556191083986353407896411091332806182, %{0 => {305909518590041931035299644016833524426, %{3 => {146325164111897696367085898820576700261, %{}}}}}}}}, %{FlameOn.Component => %{flame_on_component: 1}}, 2}, join_ref: "5", serializer: Phoenix.Socket.V2.JSONSerializer, socket: #Phoenix.LiveView.Socket<assigns: %{__changed__: %{}, csp_nonces: %{img: nil, script: nil, style: nil}, flash: %{}, live_action: :page, menu: #Phoenix.LiveDashboard.PageLive<...>, page: %Phoenix.LiveDashboard.PageBuilder{allow_destructive_actions: false, info: nil, module: FlameOn.DashboardPage, node: :nonode@nohost, params: %{"page" => "flame_on"}, route: :flame_on, tick: 0}}, endpoint: TimberWeb.Endpoint, id: "phx-F33SQhksgdR0xQAI", parent_pid: nil, root_pid: #PID<0.1699.0>, router: TimberWeb.Router, transport_pid: #PID<0.1696.0>, view: Phoenix.LiveDashboard.PageLive, ...>, topic: "lv:phx-F33SQhksgdR0xQAI", upload_names: %{}, upload_pids: %{}}
:erpc

```

How should I fix this issue? Thanks!

**Comment by andiechu** [comment]
Sorry, solved it! I was running OTP 22 so it doesn't have this module.
